# Generated by Django 4.0.4 on 2022-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Capital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capitalalias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CapitalAlias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Continent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countryalias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CountryAlias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countrycontinent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_id', models.IntegerField()),
                ('continent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'CountryContinent',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Aliases',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Capitals',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
