version: "3"

services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "50073:8000"
  frontend:
    build: ./frontend
    restart: always
    env_file:
      - frontend/.env
    depends_on:
      - backend
    ports:
      - "50075:3000"
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
