version: "3"

services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "50073:8000"
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "50074:3000"
  db:
    image: mariadb:10.5.9
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    restart: unless-stopped
    env_file:
      - backend/.env
    ports:
      - "50074:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
